const forecasts=[
 {id:1,sport:'NBA',game:'Boston vs. New York',market:'Moneyline',pick:'Boston ML',odds:'-135',model:0.624,marketProb:0.574,edge:0.050,ev:0.041,grade:'A',score:'118–112',reasons:[['Opponent-adjusted net rating', '+4.8'],['Rest / travel adjustment','+1.7'],['Availability impact','+2.1'],['Market disagreement','+5.0%'],['Model uncertainty','Moderate']]},
 {id:2,sport:'MLB',game:'Los Angeles vs. Seattle',market:'Total',pick:'Under 8.5',odds:'-105',model:0.592,marketProb:0.512,edge:0.080,ev:0.071,grade:'A-',score:'4.0–3.4',reasons:[['Starting-pitcher run prevention','+3.2'],['Bullpen freshness','+1.4'],['Park / weather factor','-0.8'],['Market disagreement','+8.0%'],['Model uncertainty','Moderate']]},
 {id:3,sport:'NFL',game:'Kansas City vs. Denver',market:'Spread',pick:'Kansas City -3.5',odds:'-110',model:0.573,marketProb:0.524,edge:0.049,ev:0.040,grade:'B+',score:'27–23',reasons:[['QB efficiency projection','+2.4'],['Pressure matchup','+1.1'],['Injury adjustment','-0.6'],['Market disagreement','+4.9%'],['Model uncertainty','High']]},
 {id:4,sport:'NHL',game:'Edmonton vs. Vancouver',market:'Total',pick:'Over 6.0',odds:'-110',model:0.548,marketProb:0.524,edge:0.024,ev:0.015,grade:'C+',score:'4–3',reasons:[['Expected-goal environment','+2.0'],['Goaltending variance','+1.5'],['Schedule effect','-0.4'],['Market disagreement','+2.4%'],['Model uncertainty','High']]}
];
const cards=document.querySelector('#cards'); const reason=document.querySelector('#reasoning'); const title=document.querySelector('#reasonTitle'); const grade=document.querySelector('#grade');
function pct(x){return `${(x*100).toFixed(1)}%`}
function render(){const sport=document.querySelector('#sport').value, market=document.querySelector('#market').value; const filtered=forecasts.filter(f=>(sport==='All Sports'||f.sport===sport)&&(market==='All Markets'||f.market===market)); document.querySelector('#edgeCount').textContent=filtered.filter(f=>f.edge>=.03).length; cards.innerHTML=filtered.map(f=>`<article class="card" data-id="${f.id}"><div class="card-top"><span class="sporttag">${f.sport} · ${f.market}</span><span class="edge">+${pct(f.edge)}</span></div><div class="match">${f.game}</div><div class="pick"><b>${f.pick}</b> · ${f.odds}</div><div class="bar"><i style="width:${f.model*100}%"></i></div><div class="stats"><div><span>MODEL</span><b>${pct(f.model)}</b></div><div><span>MARKET</span><b>${pct(f.marketProb)}</b></div><div><span>EV</span><b>+${pct(f.ev)}</b></div></div></article>`).join('')||'<div class="empty">No forecasts meet the selected filters.</div>'; document.querySelectorAll('.card').forEach(c=>c.onclick=()=>select(+c.dataset.id)); if(filtered[0])select(filtered[0].id)}
function select(id){const f=forecasts.find(x=>x.id===id); document.querySelectorAll('.card').forEach(c=>c.classList.toggle('selected',+c.dataset.id===id)); title.textContent=`${f.game} · ${f.pick}`; grade.textContent=f.grade; reason.innerHTML=f.reasons.map(([a,b])=>`<div class="reason-row"><span>${a}</span><span>${b}</span></div>`).join('')+`<div class="reason-row"><span>Projected outcome</span><span>${f.score}</span></div>`}
document.querySelector('#refresh').onclick=()=>{document.querySelector('#refresh').textContent='✓ Updated';setTimeout(()=>document.querySelector('#refresh').textContent='↻ Refresh',900)}; document.querySelector('#sport').onchange=render; document.querySelector('#market').onchange=render; render();